### ISSUE TITLE
There is a problem with the configuration environment, can you provide requirement.txt?

### ISSUE THREAD

**Issue by Daiqh1** [BrisksHan/NE-DTIP#1]
![图片](https://user-images.githubusercontent.com/76582524/147355801-f8bc2f48-02b0-49bb-94aa-6e5dd89eaf7c.png)

**Comment by BrisksHan** [comment]
Sorry for the trouble, I forgot to upload this file.

It has been uploaded now. I have tested the files in repository, it should have worked. 

For other packages, the version of sklearn should be at least 0.23.2 and the version of gensim should be at least 3.8.1. Python version 3.6.10.
